### ISSUE TITLE
Possible to bring in vehicles?

### ISSUE THREAD

**Issue by simonk83** [bmgjet/Sav.Edit#2]
Just used this for the first time and everything appears to have gone well (thanks!), but just realised that everyone has lost their mini's and cars. Just curious if it's possible to add an option to pull those in from the old save as well?

**Comment by bmgjet** [comment]
Not really posiable without using a plugin or by breaking how they work. Since the timedate of your new save is vastly different from the orignal your importing from they would all be fully decayed and despawned before the server had even finished booting the new sav. They continue to decay even when server is offline based on the time and date in the sav file unlike players which when sleeping dont starve ect.
So to do it Id have to make decay disabled on them then all the players would end up with invinsable minis.
Cars would be even worse since then all the object and modules would have to be linked up and would end up being invinsable. Such as if they had guns inside the cars storage the guns would never break.

**Comment by simonk83** [comment]
haha fair enough!
